### ISSUE TITLE
Hey nice to meet you

### ISSUE THREAD

**Issue by R3VoLuT1OneR** [joshmurrayeu/laravel-doctrine-json-api#4]
Hey, 

Just found your package in google searching for my own library :)

I want you to know that I am and actually company I am working on working on Laravel Doctrine ORM JSON:API package.

Here it is:
https://github.com/ScholarshipOwl/laravel-doctrine-jsonapi

In our company we use JSON:API + Doctrine + Laravel for almost 6 years already.
Library above is actually successor of the this libraries:
https://github.com/R3VoLuT1OneR/doctrine-rest
https://github.com/R3VoLuT1OneR/laravel-doctrine-rest

Just wanted to share this with you, maybe you find it helpful and inspiring.

**Comment by joshmurrayeu** [comment]
Hey, thanks for stopping by.
I'll have a look over the above package over the next few days. Cheers!
